### ISSUE TITLE
(Shopping Cart) Add entries in gitignore file for Java, IDEA, Gradle, Maven, Micronaut Project

### ISSUE THREAD

**Issue by csankhala** [csankhala/ShoppingCartService#9]
Hi,
Please replace current .gitignore file with https://github.com/csankhala/CustomerService/blob/develop/.gitignore

**Comment by slimane-deb** [comment]
Hi @csankhala would you assign this to me as it will be my first on github

**Comment by slimane-deb** [comment]
Hi @csankhala, can you approve #12 ?
